export const COLS_ELEMENT_INIT = 'COLS_ELEMENT_INIT';
export const COLS_INIT_STARTED = 'COLS_INIT_STARTED';
export const COLS_INIT_FINISHED = 'COLS_INIT_FINISHED';
export const COLS_MOUSEMOVE = 'COLS_MOUSEMOVE';
export const COLS_MOUSEDOWN = 'COLS_MOUSEDOWN';
export const COLS_MOUSEUP = 'COLS_MOUSEUP';
export const COLS_MOUSEOUT = 'COLS_MOUSEOUT';
export const COLS_MOUSEOVER = 'COLS_MOUSEOVER';
